### ISSUE TITLE
Add link to returned standards in webUI

### ISSUE THREAD

**Issue by wmburke** [nasa-jpl/ASSESS#1]

**Comment by giuseppetotaro** [comment]
@wmburke, we could split this in two two issues:

1. Provide a way for users to view the recommended standards.
2. Provide a way for users to view/search the referenced standards.

Specifically, the second issue is more complex because of two aspects:

- Standard references are extracted with a confidence level.
- Standard cited in SoWs could not be included in the internal standard database.

I would give more priority to the first issue ("Provide a way for users to view the recommended standards"). The recommend standards are available because we used to build the model.

**Comment by wmburke** [comment]
@giuseppetotaro You are correct and I should have been more specific. I only intended that we should provide a link to the recommended standards - we should do nothing with the returned standards at this point.

For the recommended standards, if we have public links, we should link to more info about them. In addition, I was thinking we should provide the ability to click to expand a region that contains the abstract or scope or whatever appropriate overview we have from the standard right in the interface. This is what I heard Kai-Dee asking for yesterday, so we should do both.

**Comment by giuseppetotaro** [comment]
@wmburke, I and @asitang will work on this issue in order to provide the link to the suggested standard. We will add the direct link for each crawled standard so that it can be retrieved while building the model and provided to the user along with results. Please keep in mind that the link will work until the website of the standard organization/library will keep the same structure. This could be a limitation of this approach.

**Comment by wmburke** [comment]
duplicated by #34 and #35
