### ISSUE TITLE
Standards index and dashboard

### ISSUE THREAD

**Issue by giuseppetotaro** [nasa-jpl/ASSESS#27]
# User Story

Standards index and dashboard

**Priority**: 2
**Estimate**: 2

## Description

**_As a_** Team member 

**_I want to_** index and store metadata about standards

**_so that_** I can retrieve information about standards though a Kibana dashboard

### Acceptance Criterion 1

**_Given_** a ES engine configured with a schema tailored for standard documents

**_When_** I index one or more standard documents used for training the model

**_Then_** I should be able to store to and retrieve from the index the metadata about the provided standards

### Acceptance Criterion 2

**_Given_** a running instance of ES engine

**_When_** I open the URL to the Kibana dashboard

**_Then_** I should be able to visualize the stastistics related to the provided standards

**Comment by wmburke** [comment]
So again, this is the JPL team or the team of people that will use the software? What is the purpose of being able to visualize the standards?

**Comment by giuseppetotaro** [comment]
@wmburke, this should be a new feature for the software users. The purpose is to store all the details about the collected standards within a specific index so that we can use it to provide the information on demand to the users and build a dashboard on top of this index for showing, for example, how many standards have been used to train the model.

**Comment by wmburke** [comment]
Got it. So, let me propose the following:

First, this should be written from the perspective of

**As a** end user of the software,
**I want to** be able to see what standards are included in the trained model, along with statistics about those standards,
**So that** I can understand the current database, verify that the system is working as expected, and identify missing standards that need to be included.

(accepting this may require some modifications to the Acceptance Criteria)

Secondly, should there be a separate issue for setting up the database and ensuring that training data goes into it so that this one can focus on displaying the data?

Maybe #26 should be considered more formally, eg as a critical piece of the software instead of just something for the developers to utilitize.

Thoughts?

**Comment by giuseppetotaro** [comment]
Issue #26 currently refers to our need of having a temporary store for all the standards that we use.

With regard to the statistics, I would suggest to create another user story. In my opinion, a user story including both indexing and statistics could not be completed in one iteration.

**Comment by wmburke** [comment]
@giuseppetotaro So should I tweak the above User Story to be the following:

**As a** end user of the software,
**I want to** be able to see what standards are included in the trained model, along with statistics about those standards,
**So that** I can understand the current database, verify that the system is working as expected, and identify missing standards that need to be included.

...and also modify the Acceptance Criteria to match?

**Comment by wmburke** [comment]
Oh! I see I should also remove the statistics from this to create a new issue related to that, right?

**Comment by giuseppetotaro** [comment]
@wmburke, you can change this. I am bit confused about the last part of the "so that" clause, when you write "verify that the system is working as expected, and identify missing standards that need to be included". I am not sure that the dashboard could be the right way to verify that the system is working as expected and identify missing standards.
